(feature) Option to dowload artifacts
azohra/gitrise.sh pull request #33
Opened 2021-10-01 15:06 UTC by alexist

Add on option to download artifacts at the end of the build.

Usage 
`gitrise.sh -a token -s project_slug -w workflow -b branch -D output_dir`

2021-11-24 18:03 UTC, PorterHoskins commented
I downloaded this and tried it. Works great! One suggestion I would make is have the script create the output directory if it doesn't exist.

2021-11-29 08:36 UTC, alexist commented
Thanks, this is fixed now, output dir is created automatically

2021-12-29 15:04 UTC, shaddeen commented
Any chance we can get this merged?

2022-06-04 23:56 UTC, Azbagheri requested changes
Thank you for your contribution! Please address the comments I’ve left on the PR and we can take it from there.

2022-06-04 23:56 UTC, Azbagheri commented on README.md
> +  -D, --download      <string>    Download artifacts to specified directory"
Please use -o , --output for retrieving the build artifacts

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +download_artifacts() {
For consistency, please use the function keyword in front of the function name

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +    OUTPUT_DIR=${DOWNLOAD_DIR:-'./'}
Let's use a folder named artifacts for the default directory instead of the current directory `.`. This way all the artifacts will be stored in one place and users can easily gitignore the folder

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +    response=$(eval "$command")
Please use the keyword local for the variables defined inside the function

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +    response=$(eval "$command")
Please use the keyword local for the variables defined inside the function

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +    artifacts_slug=$(echo "$response" | jq --raw-output '.data[] .slug')
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +    artifacts_slug=$(echo "$response" | jq --raw-output '.data[] .slug')
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      command="curl --silent -X GET https://api.bitrise.io/v0.1/apps/$PROJECT_SLUG/builds/$build_slug/artifacts/$artifact_slug \
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      command="curl --silent -X GET https://api.bitrise.io/v0.1/apps/$PROJECT_SLUG/builds/$build_slug/artifacts/$artifact_slug \
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      response=$(eval "$command")
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      response=$(eval "$command")
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      artifact_url=$(echo "$response" | jq --raw-output '.data.expiring_download_url')
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      artifact_url=$(echo "$response" | jq --raw-output '.data.expiring_download_url')
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      artifact_name=$(echo "$response" | jq --raw-output '.data.title')
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      artifact_name=$(echo "$response" | jq --raw-output '.data.title')
local keyword pls

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      echo "Downloading $artifact_name from $artifact_url"
Don't think it's necessary to log the URLs.

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      echo "Downloading $artifact_name from $artifact_url"
Don't think it's necessary to log the URLs.

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      echo "Download artifact meta data $artifact_slug"
Let's log the artifact name instead of the artifact slug.

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +      echo "Download artifact meta data $artifact_slug"
Let's log the artifact name instead of the artifact slug.

2022-06-04 23:56 UTC, Azbagheri commented on gitrise.sh
> +    download_artifacts
We should only run the function if the corresponding option is passed:
if [ "$DOWNLOAD_ARTIFACTS" = "true" ]

2022-09-22 18:18 UTC, D3icidal commented
Looking forward to this!

2022-10-31 13:28 UTC, azedo commented
@alexist any chance to review the suggested changes? 👍

2024-03-04 16:07 UTC, Azbagheri commented
Closing this PR as this feature is released in the latest version of Gitrise (v0.9.1). You can learn more about the feature [here](https://github.com/Tumiya/gitrise?tab=readme-ov-file#downloading-build-artifacts)

2024-03-04 16:08 UTC, closed without merging

2024-03-04 16:11 UTC, Azbagheri commented
Closing this PR as this feature is released in the latest version of Gitrise (v0.9.1). You can learn more about the feature [here](https://github.com/Tumiya/gitrise?tab=readme-ov-file#downloading-build-artifacts)